picom-trans: Use only getopts. No manual parsing.
All arguments shall be parsed by getopts. Long arguments shall be
transformed into POSIX-compatible ones before invoking getopts.

diff --git a/bin/picom-trans b/bin/picom-trans
--- a/bin/picom-trans
+++ b/bin/picom-trans
@@ -33,7 +33,7 @@ function print_usage
   echo ""
   echo "Options:"
   echo "  -h, --help                Print this help message."
-  echo "  -o, --opacity OPACITY     Specify the new opacity value in range 1-100 for the window. If"
+  echo "  -o, --opacity OPACITY     Specify the new opacity value in range 0-100 for the window. If"
   echo "                            prefixed with + or -, increment or decrement from the current"
   echo "                            opacity of the target window."
   echo ""
@@ -54,8 +54,54 @@ function print_usage
 
 function parse_args
 { #{
-  while test $# -gt 0; do
 
+  # Iterate over every option and convert
+  # longopts (GNU) into POSIX-compatible opts
+  i=1       # because we start from "$1", not from "$0"
+  while [ $i -le $# ]
+  do
+    # Catch invalid options
+    case "$1" in
+      (--opacity=|--name=|--window=)
+        echo "$0: option ${1%=} needs a value" >&2
+        exit 1;;
+      (--opacity|--name|--window)
+        test $i -eq $# \
+          && echo "$0: option $1 needs a value" >&2 \
+          && exit 1;;
+    esac
+
+    # Separate  "--ARG=VAL"  into  "--ARG" "VAL"
+    case "$1" in
+      (--opacity=*|--name=*|--window=*)
+        ARG="$(echo "$1" | sed -E 's/(--[^=]+)=.*$/\1/')"
+        VAL="${1##${ARG}=}"
+        shift && set -- "$ARG" "$VAL" "$@"
+    esac
+
+    # Turn into short form
+    case "$1" in
+      (--help|--opacity|--get|--delete|--toggle|--reset|--select|--current|--name|--window)
+        ARG=${1#-}                      # remove one '-' from prefix
+        ARG="$(echo $ARG | cut -c -2)"  # get first two characters
+        shift && set -- "$ARG" "$@"
+    esac
+
+    # If the argument still starts with --, it is an invalid argument
+    case "$1" in
+      (--*)
+        echo "$0: illegal option $1" >&2
+        exit 1
+    esac
+
+    # Prepare for next iteration
+    ARG="$1"
+    shift && set -- "$@" "$ARG"
+    i=$(( i + 1 ))
+  done
+
+
+  while test $# -gt 0; do
     # 15 +15 -15 are opacity values
     # filter them out here, otherwise getopts will complain
     if echo "$1" | grep -qE '^[+-]?[[:digit:]]+%?$'; then
@@ -64,71 +110,8 @@ function parse_args
       continue
     fi
 
-    case "$1" in
-      (-h|--help) print_usage; exit 0;;
-      (-o|--opacity) target_opacity=$2; shift 2; continue;;
-
-      (-g|--get)    action=get;    shift; continue;;
-      (-d|--delete) action=delete; shift; continue;;
-      (-t|--toggle) action=toggle; shift; continue;;
-      (-r|--reset)  action=reset;  shift; continue;;
-
-      (-s|--select)
-        winidtype=
-        winid=
-        shift
-        continue ;;
-
-      (-c|--current)
-        winidtype=-id
-        winid="$(get_focused_window_id)"
-        shift
-        continue ;;
-
-      (-n|--name)
-        if test -z "$2"; then
-          echo "Option $1 requires an argument" >&2
-          exit 1
-        fi
-        winidtype=-name
-        winid="$2"
-        shift
-        continue ;;
-
-      (-w|--window)
-        if test -z "$2"; then
-          echo "Option $1 requires an argument" >&2
-          exit 1
-        fi
-        winidtype=-id
-        winid="$2"
-        shift
-        continue ;;
-
-      (--opacity=*)
-        target_opacity="$(echo "$1" | sed -E 's/^[^=]+=$//')"
-        shift
-        continue ;;
-
-      (--name=*)
-        winidtype=-name
-        winid="$(echo "$1" | sed -E 's/^[^=]+=$//')"
-        shift
-        continue ;;
-
-      (--window=*)
-        winidtype=-id
-        winid="$(echo "$1" | sed -E 's/^[^=]+=$//')"
-        shift
-        continue ;;
-
-    esac
-
-
-    # Use getopts to catch any argument we might have missed.
-    # i.e. arguments like '-cg' or '-o80' or even '-co+15'
     OPTIND=1
-    while getopts 'ho:gdtrscn:w:' OPTION "$@"
+    while getopts ':ho:gdtrscn:w:' OPTION
     do
       case "$OPTION" in
         (h) print_usage; exit 0;;
@@ -140,11 +123,21 @@ function parse_args
         (s) winidtype=;         winid=;;
         (c) winidtype=-id;      winid="$(get_focused_window_id)";;
         (n) winidtype=-name;    winid="$OPTARG";;
-        (w) winidtype=-window;  winid="$OPTARG";;
-        (\?) exit 1;;
+        (w) winidtype=-id;      winid="$OPTARG";;
+        (\?)
+          # This might not be an invalid argument.
+          # It could be an opacity value.
+          #
+          # If it is an opacity value,  just break.
+          # It will be handled at next iteration of the loop.
+          if echo $OPTARG | grep -q '[[:digit:]]'
+          then break
+          else echo "$0: illegal option: $1" >&2 && exit 1
+          fi
       esac
-      # If getopts goes to the second argument, stop parsing with getopt
-      test $OPTIND -ge 3  && break
+
+      # If getopts goes to the second argument, stop
+      test $OPTIND -ge 3 && break
     done
     shift
   done
@@ -263,7 +256,10 @@ function set_opacity
 { #{
   if ! echo "$target_opacity" | grep -qE '^[+-]?[[:digit:]]+%?$'
   then
-    echo "Invalid opacity specified: $target_opacity" >&2
+    if test -z "$target_opacity"
+    then echo "No opacity specified" >&2
+    else echo "Invalid opacity specified: $target_opacity" >&2
+    fi
     exit 1
   fi
 
